### PR TITLE
Updates version numbers of npm modules to current versions.

### PR DESCRIPTION
**Pull request by pchorus**
Updates npm module grunt to version 1.0.1. Its dependencies are updates accordingly.
Peer dependency for grunt allows grunt 1.0.1 as well.

### CODE REVIEW

**Comment by sda399** [comment]
@pchorus any updates on this pull request?

**Comment by pchorus** [comment]
@sda399 No. Still waiting for a message or merge.

**Comment by jwvdiermen** [comment]
I'm not using Grunt anymore, so I'm not sure if everything is OK. I suggest bumping the version to 1.0.0 since the dependencies also got a major version update. If that's OK, I'll publish this version later tonight.

**Comment by sda399** [comment]
thanks for the update.
I think it would be nice to put note on the home page, to inform about the state of this plugin as abandoned, deprecated or as not maintained.

**Comment by jwvdiermen** [comment]
I'll still be accepting pull requests, but I'll put a note in the readme.

**Pull request merged**
